### ISSUE TITLE
Updtr failed

### ISSUE THREAD

**Issue by shaunstanislaus** [peerigon/updtr#10]
i think you need to fix this, my documentjs is updated to 0.3.6, but it rolled back for some reason.

```bash
shaunstanislaus in ~
≥ updtr                                                                                                                                                                                             10:27
Found 21 outdated modules

Starting to update your modules...
1/21 	 ● documentjs rolling back... ⠋ /usr/local/lib/node_modules/updtr/bin/updtr:28
        throw err;
        ^

Error: Command failed: /bin/sh -c npm i documentjs@undefined --save-dev
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/shaunstanislaus/homebrew/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "i" "documentjs@undefined" "--save-dev"
npm ERR! node v5.1.0
npm ERR! npm  v3.5.0

npm ERR! No compatible version found: documentjs@undefined
npm ERR! Valid install targets:
npm ERR! 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.3.0-pre.5, 0.3.0-pre.4, 0.3.0-pre.3, 0.3.0-pre.2, 0.3.0-pre.1, 0.3.0-pre.0, 0.2.1, 0.2.0, 0.1.3, 0.1.2, 0.1.1, 0.1.0
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shaunstanislaus/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by matthaias** [comment]
It looks like `updtr` could not find a installed version, because there was some error and so `updtr` tried to roll back your documentjs. This taks fails because of a `undefined` current version:

`Error: Command failed: /bin/sh -c npm i documentjs@undefined --save-dev` 

Is it possible that `documentjs` was not installed before running `updtr`? I just saw that this is not checked. I will figure something out for this problem.

**Comment by matthaias** [comment]
Can you try this branch? https://github.com/peerigon/updtr/tree/bugfix/skip-not-installed-modules

**Comment by simplyianm** [comment]
I'm getting the same error

**Comment by matthaias** [comment]
Should be solved with `v.0.1.4`.

**Comment by markogresak** [comment]
Just a hint for someone else having the problem with failed updates, make sure your `npm test` passes before running `updtr`. Just saying that for people like myself who don't always read the docs :smile:
