### ISSUE TITLE
Is it possible to get the output (stdout/stderr) from the npm test command?

### ISSUE THREAD

**Issue by alexlawrence** [peerigon/updtr#20]
We have a quite a lot of specs executed upon "npm test" and would like to see the test output in order to know why a dependency could not be updated. Is it possible?

**Comment by camsjams** [comment]
+1

**Comment by matthaias** [comment]
Yes, i think we can do this. I will add this in the first days of 2016 :)

**Comment by medialwerk** [comment]
+1

**Comment by matthaias** [comment]
Published as `v0.1.7`.

Output is something like this:

```
5/5 	 ● xunit-file 0.0.9 failed

> module@version test 
> mocha -R dot -c



  ․

  0 passing (2s)
  1 failing

  1) TestCase

      AssertionError: expected { Object (stdout, stderr) } to not equal { Object (stdout, stderr) }
      + expected - actual


      at assertEqual (node_modules/chai/lib/chai/core/assertions.js:470:12)
      at ctx.(anonymous function) (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at doAsserterAsyncAndAddThen (node_modules/chai-as-promised/lib/chai-as-promised.js:292:33)
      at null.<anonymous> (node_modules/chai-as-promised/lib/chai-as-promised.js:251:21)
      at ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/overwriteMethod.js:48:33)
      at Context.<anonymous> (test/main.test.js:17:43)
```

**Comment by meaku** [comment]
:+1:

**Comment by camsjams** [comment]
:shipit: thanks!

**Comment by medialwerk** [comment]
Thanks :-)
