### ISSUE TITLE
Fail using npm@4.0.1

### ISSUE THREAD

**Issue by mastilver** [peerigon/updtr#53]
On:
- Windows 10
- Node 6.8.1
- Npm 4.0.1

Trace:

```
Looking for outdated modules... ⠲ C:\Users\ThomasSileghem\AppData\Roaming\nvm\v6.8.1\node_modules\updtr\bin\updtr:38
        throw err;
        ^

Error: Command failed: npm outdated --json --long --depth=0

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by mastilver** [comment]
I guess it's happening because of: https://github.com/npm/npm/pull/14013

**Comment by mastilver** [comment]
I'm ready to send a PR but, shouldn't `updtr` require it's own `npm` rather that use the global one, it would prevent this kind of issue
